apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: sock-shop
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          # TODO: replace with your pushed image (e.g., nbthecool8/hello-cicd:latest)
          image: nbthecool8/hello-cicd:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP
              value: "demo"
            - name: VER
              value: "v1"
            - name: PORT
              value: "8080"
            - name: METRICS_PORT
              value: "9000"
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
