apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  namespace: betamonitoring
  labels:
    # This label must match Prometheus' serviceMonitorSelector
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo
  namespaceSelector:
    matchNames:
      - sock-shop
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
