{
 "title": "Demo App Overview",
 "tags": [ "demo" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "In-Progress (by path)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(demo_inprogress)" }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum by (path,method,code) (rate(demo_hits_total[1m]))"
    }
   ]
  },
  {
   "title": "Request Latency (p50/p90/p99)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le,path,method) (rate(demo_request_seconds_bucket[1m])))",
     "legendFormat": "p50 {{path}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,path,method) (rate(demo_request_seconds_bucket[1m])))",
     "legendFormat": "p90 {{path}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le,path,method) (rate(demo_request_seconds_bucket[1m])))",
     "legendFormat": "p99 {{path}}"
    }
   ]
  },
  {
   "title": "Votes per Poll Option (rate)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (poll_id,option) (rate(demo_poll_votes_total[1m]))"
    }
   ]
  },
  {
   "title": "Background CPU Work (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(demo_compute_seconds_bucket[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Active Polls / A/B Flags",
   "type": "stat",
   "gridPos": { "x": 0, "y": 19, "w": 8, "h": 3 },
   "targets": [
    { "expr": "demo_polls_total" },
    { "expr": "demo_ab_flags_total" }
   ]
  },
  {
   "title": "Node CPU (host)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 19, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[2m])"
    }
   ]
  },
  {
   "title": "Container CPU - app",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 22, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_container_name!=\"\",name!=\"\",id!=\"\",container!=\"\",image!=\"\", container_label_com_docker_compose_service=\"app\"}[2m])"
    }
   ]
  }
 ]
}