name: Build & Deploy to Local K8s
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd:latest

      - name: Patch image tag in manifest
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd:${{ github.sha }}"' k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
